# Generated by Django 3.1.3 on 2020-11-16 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subject', '0001_initial'),
        ('Groups_faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shcedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chetverg_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chetverg1', to='Subject.subject')),
                ('chetverg_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chetverg2', to='Subject.subject')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups_faculties.groups')),
                ('patniza_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patniza1', to='Subject.subject')),
                ('patniza_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patniza2', to='Subject.subject')),
                ('pon_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pon1', to='Subject.subject')),
                ('pon_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pon2', to='Subject.subject')),
                ('sreda_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sreda1', to='Subject.subject')),
                ('sreda_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sreda2', to='Subject.subject')),
                ('vtornik_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vtornik1', to='Subject.subject')),
                ('vtornik_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vtornik2', to='Subject.subject')),
            ],
        ),
    ]
