# Generated by Django 3.1.3 on 2020-11-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0001_initial'),
        ('Shcedule', '0002_auto_20201116_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shcedule',
            name='chetverg_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chetverg1', to='Subject.subject'),
        ),
        migrations.AlterField(
            model_name='shcedule',
            name='chetverg_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chetverg2', to='Subject.subject'),
        ),
        migrations.AlterField(
            model_name='shcedule',
            name='patniza_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patniza1', to='Subject.subject'),
        ),
        migrations.AlterField(
            model_name='shcedule',
            name='patniza_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patniza2', to='Subject.subject'),
        ),
        migrations.AlterField(
            model_name='shcedule',
            name='pon_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pon1', to='Subject.subject'),
        ),
        migrations.AlterField(
            model_name='shcedule',
            name='pon_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pon2', to='Subject.subject'),
        ),
        migrations.AlterField(
            model_name='shcedule',
            name='sreda_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sreda1', to='Subject.subject'),
        ),
        migrations.AlterField(
            model_name='shcedule',
            name='sreda_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sreda2', to='Subject.subject'),
        ),
        migrations.AlterField(
            model_name='shcedule',
            name='vtornik_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vtornik1', to='Subject.subject'),
        ),
        migrations.AlterField(
            model_name='shcedule',
            name='vtornik_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vtornik2', to='Subject.subject'),
        ),
    ]
