# Generated by Django 3.1.3 on 2020-11-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('Task', '0002_auto_20201115_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='student',
        ),
        migrations.AddField(
            model_name='task',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_task', to='users.student'),
        ),
    ]
